spring:
  application:
    name: lesson-backend
  profiles:
    active: test   # 디폴트 프로파일을 test로 설정

server:
  port: 8080

logging:
  level:
    root: INFO

payment:
  outbox:
    publish-fixed-delay-ms: 5000
  refund:
    retry-fixed-delay-ms: 10000
  booking-completion:
    retry-fixed-delay-ms: 10000
